### ISSUE TITLE
Users can search for a recipe from the site and view a list of results

### ISSUE THREAD

**Issue by samlee0258** [samlee0258/RecipeFinder#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search for a recipe from the site and view a list of results
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a home page with a search bar that allows users to search for a recipe and view the search results. Clicking on the menu button in the navbar brings out a drawer component that allows the user to navigate back to the home page to search for another recipe. The web page should have a responsive display for mobile and desktop.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="652" alt="Screenshot 2023-04-18 at 3 04 29 PM" src="https://user-images.githubusercontent.com/110208589/232915366-ad248d94-bc5c-4ae3-9525-a3511ea55aed.png">
<img width="735" alt="Screenshot 2023-04-18 at 3 05 23 PM" src="https://user-images.githubusercontent.com/110208589/232915518-3762377d-3581-4679-bf3a-b4c14a160774.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Add in dummy data to the other tables in the database.

### ☁️ Server Tasks

- [x] Update `server.js` to pull data from the database.
- [x] Test with HTTPie to see if the correct output or error is being shown.
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add necessary elements to match the figma example.
    - [x] Add nav bar with the name of the app and a `menu button`.
    - [x] Add Title to the home page.
    - [x] Create a search `input` with a search `button`.
    - [x] Add in `background image`.
    - [x] Add `css` styling.

- [x] Create a component for the search input and button.
- [x] Create a component for the menu button.
    - [x] When `clicked` open a menu sidebar.
    - [x] Has a link to the `home` screen.
    - [x] Clicking on the `X` closes the sidebar.

### 🧑‍⚕️ Clean Up Tasks

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
