### ISSUE TITLE
Users can click on a searched recipe for more info

### ISSUE THREAD

**Issue by samlee0258** [samlee0258/RecipeFinder#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can click on a searched recipe to look at the recipe’s ingredient list, calories, and serving size
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When users click on the recipe card it will render a single card of the 'clicked' recipe and show more details on the selected recipe. The ingredients list, calories, and serving size for the selected recipe will be displayed.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="652" alt="Screenshot 2023-04-18 at 3 52 47 PM" src="https://user-images.githubusercontent.com/110208589/232922078-68f7a009-7fe7-4dc4-be98-9ddd90f2ac43.png">
<img width="743" alt="Screenshot 2023-04-18 at 3 53 19 PM" src="https://user-images.githubusercontent.com/110208589/232922095-2506148e-d09b-440a-8d2a-c27de28dd77a.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
