### ISSUE TITLE
Users can navigate to the website with the recipe instructions

### ISSUE THREAD

**Issue by samlee0258** [samlee0258/RecipeFinder#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can click on a button to take them to the website where it has the recipe instructions
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user searches for a recipe and selects the desired recipe for more info, there will be a button available to take the user to the website with the recipe instructions.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="654" alt="Screenshot 2023-04-18 at 4 03 20 PM" src="https://user-images.githubusercontent.com/110208589/232923445-11c2dd2d-39f1-4829-aee6-e7664a9fb4a8.png">
<img width="742" alt="Screenshot 2023-04-18 at 4 03 44 PM" src="https://user-images.githubusercontent.com/110208589/232923454-03d6d3d3-c33d-4761-a19b-9c0fd8c57eb6.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] ...
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
