### ISSUE TITLE
Users can view their favorites list

### ISSUE THREAD

**Issue by samlee0258** [samlee0258/RecipeFinder#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view their favorites list where their favorited recipes will be displayed in

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Add a link in the menu sidebar that takes the user to their favorites list. If there is no favorited recipes yet, display text telling the user they have no favorites yet.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="488" alt="Screenshot 2023-04-18 at 4 09 10 PM" src="https://user-images.githubusercontent.com/110208589/232924382-3a629917-f207-40d6-b8a3-65d3509f6c2f.png">
<img width="741" alt="Screenshot 2023-04-18 at 4 09 27 PM" src="https://user-images.githubusercontent.com/110208589/232924389-48ca86ab-c38d-408a-975c-bb28ec5dc61c.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] ...
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
