### ISSUE TITLE
Users can toggle recipes to their favorites or remove from their favorites

### ISSUE THREAD

**Issue by samlee0258** [samlee0258/RecipeFinder#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can toggle the favorites button to add or delete the recipe from their favorites list
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a toggle button that can allow users to add the recipe to their favorites list or remove it from the list. The button will be displayed with the recipe link button and the detailed info on the selected recipe.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="925" alt="Screenshot 2023-04-18 at 4 18 52 PM" src="https://user-images.githubusercontent.com/110208589/232925440-fa2638cf-4c31-4b7a-a8f0-e34dc47556a6.png">
<img width="907" alt="Screenshot 2023-04-18 at 4 20 22 PM" src="https://user-images.githubusercontent.com/110208589/232925453-3787f29b-7f08-4a7e-97af-786c02f25b66.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

 
- [ ] ...
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
